/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import ClassFiles.Admin;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dilshan Wimalasuriya
 */
public class AdminUpdate extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdminRegister
     * @param name
     * @param username
     * @param tphone
     * @param mail
     */

    private String username1;
    private String name1;
    private String mail1;
    private String phonenum1;
       public AdminUpdate() {
        initComponents();
    }
    public AdminUpdate(String name,String username,String mail, String tphone) {
        initComponents();
        lname.setText(name);
        uname.setText(username);
        email.setText(mail);
        phone.setText(tphone);
        username1 = username;
        name1 = name;
        mail1 = mail;
        phonenum1 = tphone;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        uname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        resetbutton = new javax.swing.JButton();

        setBorder(null);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        jLabel11.setText("E-mail");

        jLabel12.setText("Phone");

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });

        phone.setText("947XXXXXXXX");
        phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFocusLost(evt);
            }
        });
        phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneMouseClicked(evt);
            }
        });
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneKeyPressed(evt);
            }
        });

        jLabel7.setText("Full Name");

        register.setText("Update");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });

        jLabel8.setText("Username");

        resetbutton.setText("Reset");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(87, 87, 87))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(484, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(register)
                        .addGap(36, 36, 36)
                        .addComponent(resetbutton)))
                .addContainerGap(405, Short.MAX_VALUE))
        );

        setBounds(-5, -35, 1020, 581);
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusGained
        phone.setText("947");
    }//GEN-LAST:event_phoneFocusGained

    private void phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusLost

    }//GEN-LAST:event_phoneFocusLost

    private void phoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneMouseClicked
        phone.setText("947");
    }//GEN-LAST:event_phoneMouseClicked

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyPressed

    }//GEN-LAST:event_phoneKeyPressed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed

        
        
        
        String name = lname.getText();
        String unam = uname.getText();
        String emai = email.getText();
        String phon = phone.getText();

        int atchar = -2;
        int dot = -1;
        for(int x = 0; x< emai.length(); x++)
        {
            if(emai.charAt(x) == '@')
            {
                atchar = x;
            }
            else if (emai.charAt(x) == '.')
            {
                dot = x;
            }
        }

        boolean checkphone = false;

        for (int y=0; y<phon.length(); y++)
        {
            if(Character.isDigit(phon.charAt(y)))
            {
                checkphone = true;
            }
            else
            {
                checkphone = false;
                break;
            }
        }

        if(name.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter a Name");
        }
        else if(unam.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter a Username");
        }
        else if(emai.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter an E-mail");
        }
        else if(phon.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter a Phone number");
        }  
        else if ((dot<atchar) || (dot == -1) || (atchar == -2))
        {
            JOptionPane.showMessageDialog(null, "Entered Email is not an valid Email address");
        }
        else if((phon.length()!=11) || (phon.charAt(0) != '9') || (phon.charAt(1) != '4') || (phon.charAt(2) != '7') || (checkphone == false))
        {
            JOptionPane.showMessageDialog(null, "Invalid Phone number. You must use 94700000000 Format");
        }
        else
        {
            int x = JOptionPane.showConfirmDialog(null,"Do You Really Want To Update The Selected User Details?");
            int checkusername = unam.compareTo(username1);
            int checkemail =emai.compareTo(mail1);
            boolean usernamechanges = true;
            boolean emailchanges = true;
            if(x==0)
            {
                boolean status = false;
                boolean find = true;
                boolean changes = false;
                Admin ad = new Admin(name,unam,emai,phon);
                if((checkemail ==0) &&(checkusername ==0) )
                {
                    try {
                      status = ad.UpdateAdmin();
                    }
                    catch (SQLException ex) {
                        Logger.getLogger(AdminsInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if(status)
                    {
                        this.dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Error! Admin Details Not Updated");
                    }
                    changes = true;
                }
                if(checkusername!=0)
                {
                    try {
                        find = ad.FindAdminFromUsername();
                    } catch (SQLException ex) {
                        Logger.getLogger(CustomerUpdate.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if(find)
                    {
                        JOptionPane.showMessageDialog(null, "Cannot Update Admim, username : "+unam+" is unavailabel, Please Enter a Different Username");
                        usernamechanges = false;
                    }
                    else
                    {
                        usernamechanges = true;
                    }
                }
                if(checkemail!=0)
                {
                    System.out.println("email");
                    try {
                        find = ad.FindAdminFromEmail();
                    } catch (SQLException ex) {
                        Logger.getLogger(CustomerUpdate.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if(find)
                    {
                        JOptionPane.showMessageDialog(null, "Cannot Update Admin, email : "+emai+" is unavailabel, Please Enter a Different email");
                        emailchanges = false;
                    }
                    else
                    {
                        emailchanges = true;
                    }
                }
                if((usernamechanges==true)&&(emailchanges==true)&&(changes==false))
                {
                    try {
                      status = ad.UpdateAdmin(username1);
                    }
                    catch (SQLException ex) {
                        Logger.getLogger(AdminsInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if(status)
                    {
                        this.dispose();
                    }
                }    
            }
        }
    }//GEN-LAST:event_registerActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
        lname.setText(name1);
        uname.setText(username1);
        email.setText(mail1);
        phone.setText(phonenum1);
    }//GEN-LAST:event_resetbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField phone;
    private javax.swing.JButton register;
    private javax.swing.JButton resetbutton;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
